include:
  entt/config:
    - com_github_skypjack_entt/src/entt/config/config.h
    - com_github_skypjack_entt/src/entt/config/macro.h
    - com_github_skypjack_entt/src/entt/config/version.h
  entt/container:
    - com_github_skypjack_entt/src/entt/container/dense_map.hpp
    - com_github_skypjack_entt/src/entt/container/dense_set.hpp
    - com_github_skypjack_entt/src/entt/container/fwd.hpp
  entt/core:
    - com_github_skypjack_entt/src/entt/core/algorithm.hpp
    - com_github_skypjack_entt/src/entt/core/any.hpp
    - com_github_skypjack_entt/src/entt/core/attribute.h
    - com_github_skypjack_entt/src/entt/core/compressed_pair.hpp
    - com_github_skypjack_entt/src/entt/core/enum.hpp
    - com_github_skypjack_entt/src/entt/core/family.hpp
    - com_github_skypjack_entt/src/entt/core/fwd.hpp
    - com_github_skypjack_entt/src/entt/core/hashed_string.hpp
    - com_github_skypjack_entt/src/entt/core/ident.hpp
    - com_github_skypjack_entt/src/entt/core/iterator.hpp
    - com_github_skypjack_entt/src/entt/core/memory.hpp
    - com_github_skypjack_entt/src/entt/core/monostate.hpp
    - com_github_skypjack_entt/src/entt/core/tuple.hpp
    - com_github_skypjack_entt/src/entt/core/type_info.hpp
    - com_github_skypjack_entt/src/entt/core/type_traits.hpp
    - com_github_skypjack_entt/src/entt/core/utility.hpp
  entt/entity:
    - com_github_skypjack_entt/src/entt/entity/component.hpp
    - com_github_skypjack_entt/src/entt/entity/entity.hpp
    - com_github_skypjack_entt/src/entt/entity/fwd.hpp
    - com_github_skypjack_entt/src/entt/entity/group.hpp
    - com_github_skypjack_entt/src/entt/entity/handle.hpp
    - com_github_skypjack_entt/src/entt/entity/helper.hpp
    - com_github_skypjack_entt/src/entt/entity/observer.hpp
    - com_github_skypjack_entt/src/entt/entity/organizer.hpp
    - com_github_skypjack_entt/src/entt/entity/registry.hpp
    - com_github_skypjack_entt/src/entt/entity/runtime_view.hpp
    - com_github_skypjack_entt/src/entt/entity/sigh_storage_mixin.hpp
    - com_github_skypjack_entt/src/entt/entity/snapshot.hpp
    - com_github_skypjack_entt/src/entt/entity/sparse_set.hpp
    - com_github_skypjack_entt/src/entt/entity/storage.hpp
    - com_github_skypjack_entt/src/entt/entity/utility.hpp
    - com_github_skypjack_entt/src/entt/entity/view.hpp
  entt:
    - com_github_skypjack_entt/src/entt/entt.hpp
    - com_github_skypjack_entt/src/entt/fwd.hpp
  entt/locator:
    - com_github_skypjack_entt/src/entt/locator/locator.hpp
  entt/meta:
    - com_github_skypjack_entt/src/entt/meta/adl_pointer.hpp
    - com_github_skypjack_entt/src/entt/meta/container.hpp
    - com_github_skypjack_entt/src/entt/meta/ctx.hpp
    - com_github_skypjack_entt/src/entt/meta/factory.hpp
    - com_github_skypjack_entt/src/entt/meta/fwd.hpp
    - com_github_skypjack_entt/src/entt/meta/meta.hpp
    - com_github_skypjack_entt/src/entt/meta/node.hpp
    - com_github_skypjack_entt/src/entt/meta/pointer.hpp
    - com_github_skypjack_entt/src/entt/meta/policy.hpp
    - com_github_skypjack_entt/src/entt/meta/range.hpp
    - com_github_skypjack_entt/src/entt/meta/resolve.hpp
    - com_github_skypjack_entt/src/entt/meta/template.hpp
    - com_github_skypjack_entt/src/entt/meta/type_traits.hpp
    - com_github_skypjack_entt/src/entt/meta/utility.hpp
  entt/platform:
    - com_github_skypjack_entt/src/entt/platform/android-ndk-r17.hpp
  entt/poly:
    - com_github_skypjack_entt/src/entt/poly/fwd.hpp
    - com_github_skypjack_entt/src/entt/poly/poly.hpp
  entt/process:
    - com_github_skypjack_entt/src/entt/process/process.hpp
    - com_github_skypjack_entt/src/entt/process/scheduler.hpp
  entt/resource:
    - com_github_skypjack_entt/src/entt/resource/cache.hpp
    - com_github_skypjack_entt/src/entt/resource/fwd.hpp
    - com_github_skypjack_entt/src/entt/resource/loader.hpp
    - com_github_skypjack_entt/src/entt/resource/resource.hpp
  entt/signal:
    - com_github_skypjack_entt/src/entt/signal/delegate.hpp
    - com_github_skypjack_entt/src/entt/signal/dispatcher.hpp
    - com_github_skypjack_entt/src/entt/signal/emitter.hpp
    - com_github_skypjack_entt/src/entt/signal/fwd.hpp
    - com_github_skypjack_entt/src/entt/signal/sigh.hpp
