include:
  entt/config:
    - com_github_skypjack_entt/src/entt/config/config.h
    - com_github_skypjack_entt/src/entt/config/macro.h
    - com_github_skypjack_entt/src/entt/config/version.h
  entt/container:
    - com_github_skypjack_entt/src/entt/container/dense_map.hpp
    - com_github_skypjack_entt/src/entt/container/dense_set.hpp
    - com_github_skypjack_entt/src/entt/container/fwd.hpp
  entt/core:
    - com_github_skypjack_entt/src/entt/core/algorithm.hpp
    - com_github_skypjack_entt/src/entt/core/any.hpp
    - com_github_skypjack_entt/src/entt/core/attribute.h
    - com_github_skypjack_entt/src/entt/core/compressed_pair.hpp
    - com_github_skypjack_entt/src/entt/core/enum.hpp
    - com_github_skypjack_entt/src/entt/core/family.hpp
    - com_github_skypjack_entt/src/entt/core/fwd.hpp
    - com_github_skypjack_entt/src/entt/core/hashed_string.hpp
    - com_github_skypjack_entt/src/entt/core/ident.hpp
    - com_github_skypjack_entt/src/entt/core/iterator.hpp
    - com_github_skypjack_entt/src/entt/core/memory.hpp
    - com_github_skypjack_entt/src/entt/core/monostate.hpp
    - com_github_skypjack_entt/src/entt/core/tuple.hpp
    - com_github_skypjack_entt/src/entt/core/type_info.hpp
    - com_github_skypjack_entt/src/entt/core/type_traits.hpp
    - com_github_skypjack_entt/src/entt/core/utility.hpp
  entt/entity:
    - com_github_skypjack_entt/src/entt/entity/component.hpp
    - com_github_skypjack_entt/src/entt/entity/entity.hpp
    - com_github_skypjack_entt/src/entt/entity/fwd.hpp
    - com_github_skypjack_entt/src/entt/entity/group.hpp
    - com_github_skypjack_entt/src/entt/entity/handle.hpp
    - com_github_skypjack_entt/src/entt/entity/helper.hpp
    - com_github_skypjack_entt/src/entt/entity/observer.hpp
    - com_github_skypjack_entt/src/entt/entity/organizer.hpp
    - com_github_skypjack_entt/src/entt/entity/registry.hpp
    - com_github_skypjack_entt/src/entt/entity/runtime_view.hpp
    - com_github_skypjack_entt/src/entt/entity/snapshot.hpp
    - com_github_skypjack_entt/src/entt/entity/sparse_set.hpp
    - com_github_skypjack_entt/src/entt/entity/storage.hpp
    - com_github_skypjack_entt/src/entt/entity/storage_mixin.hpp
    - com_github_skypjack_entt/src/entt/entity/view.hpp
  entt/graph:
    - com_github_skypjack_entt/src/entt/graph/adjacency_matrix.hpp
    - com_github_skypjack_entt/src/entt/graph/flow.hpp
    - com_github_skypjack_entt/src/entt/graph/dot.hpp
    - com_github_skypjack_entt/src/entt/graph/fwd.hpp
  entt:
    - com_github_skypjack_entt/src/entt/entt.hpp
    - com_github_skypjack_entt/src/entt/fwd.hpp
  entt/locator:
    - com_github_skypjack_entt/src/entt/locator/locator.hpp
  entt/meta:
    - com_github_skypjack_entt/src/entt/meta/adl_pointer.hpp
    - com_github_skypjack_entt/src/entt/meta/container.hpp
    - com_github_skypjack_entt/src/entt/meta/context.hpp
    - com_github_skypjack_entt/src/entt/meta/factory.hpp
    - com_github_skypjack_entt/src/entt/meta/fwd.hpp
    - com_github_skypjack_entt/src/entt/meta/meta.hpp
    - com_github_skypjack_entt/src/entt/meta/node.hpp
    - com_github_skypjack_entt/src/entt/meta/pointer.hpp
    - com_github_skypjack_entt/src/entt/meta/policy.hpp
    - com_github_skypjack_entt/src/entt/meta/range.hpp
    - com_github_skypjack_entt/src/entt/meta/resolve.hpp
    - com_github_skypjack_entt/src/entt/meta/template.hpp
    - com_github_skypjack_entt/src/entt/meta/type_traits.hpp
    - com_github_skypjack_entt/src/entt/meta/utility.hpp
  entt/platform:
    - com_github_skypjack_entt/src/entt/platform/android-ndk-r17.hpp
  entt/poly:
    - com_github_skypjack_entt/src/entt/poly/fwd.hpp
    - com_github_skypjack_entt/src/entt/poly/poly.hpp
  entt/process:
    - com_github_skypjack_entt/src/entt/process/process.hpp
    - com_github_skypjack_entt/src/entt/process/scheduler.hpp
  entt/resource:
    - com_github_skypjack_entt/src/entt/resource/cache.hpp
    - com_github_skypjack_entt/src/entt/resource/fwd.hpp
    - com_github_skypjack_entt/src/entt/resource/loader.hpp
    - com_github_skypjack_entt/src/entt/resource/resource.hpp
  entt/signal:
    - com_github_skypjack_entt/src/entt/signal/delegate.hpp
    - com_github_skypjack_entt/src/entt/signal/dispatcher.hpp
    - com_github_skypjack_entt/src/entt/signal/emitter.hpp
    - com_github_skypjack_entt/src/entt/signal/fwd.hpp
    - com_github_skypjack_entt/src/entt/signal/sigh.hpp
  ecsact:
    - ecsact_runtime/ecsact/codegen_plugin.h
    - ecsact_runtime/ecsact/codegen_plugin.hh
    - ecsact_runtime/ecsact/lib.hh
    - ecsact_runtime/ecsact/runtime.h
  ecsact/runtime:
    - ecsact_runtime/ecsact/runtime/common.h
    - ecsact_runtime/ecsact/runtime/async.h
    - ecsact_runtime/ecsact/runtime/core.h
    - ecsact_runtime/ecsact/runtime/core.hh
    - ecsact_runtime/ecsact/runtime/definitions.h
    - ecsact_runtime/ecsact/runtime/dylib.h
    - ecsact_runtime/ecsact/runtime/dynamic.h
    - ecsact_runtime/ecsact/runtime/meta.h
    - ecsact_runtime/ecsact/runtime/meta.hh
    - ecsact_runtime/ecsact/runtime/serialize.h
    - ecsact_runtime/ecsact/runtime/serialize.hh
    - ecsact_runtime/ecsact/runtime/static.h
  ecsact/codegen:
    - ecsact_runtime/ecsact/codegen/plugin_validate.hh
  ecsact/entt:
    - ecsact_rt_entt/ecsact/entt/entity.hh
    - ecsact_rt_entt/ecsact/entt/runtime.hh
    - ecsact_rt_entt/ecsact/entt/system_view.hh
    - ecsact_rt_entt/ecsact/entt/trivial_system_impl.hh
    - ecsact_rt_entt/ecsact/entt/event_markers.hh
  ecsact/entt/detail:
    - ecsact_rt_entt/ecsact/entt/detail/entt_util.hh
    - ecsact_rt_entt/ecsact/entt/detail/execution_events_collector.hh
    - ecsact_rt_entt/ecsact/entt/detail/mp11_util.hh
    - ecsact_rt_entt/ecsact/entt/detail/registry_info.hh
    - ecsact_rt_entt/ecsact/entt/detail/system_execution_context.hh
    - ecsact_rt_entt/ecsact/entt/detail/internal_markers.hh
    - ecsact_rt_entt/ecsact/entt/detail/meta_util.hh
  ecsact/cpp:
    - ecsact_lang_cpp/ecsact/cpp/type_info.hh
    - ecsact_lang_cpp/ecsact/cpp/execution_context.hh
  boost:
    - boost_mp11_files/include/boost/mp11.hpp
  boost/mp11:
    - boost_mp11_files/include/boost/mp11/algorithm.hpp
    - boost_mp11_files/include/boost/mp11/bind.hpp
    - boost_mp11_files/include/boost/mp11/function.hpp
    - boost_mp11_files/include/boost/mp11/integer_sequence.hpp
    - boost_mp11_files/include/boost/mp11/integral.hpp
    - boost_mp11_files/include/boost/mp11/list.hpp
    - boost_mp11_files/include/boost/mp11/map.hpp
    - boost_mp11_files/include/boost/mp11/mpl.hpp
    - boost_mp11_files/include/boost/mp11/mpl_list.hpp
    - boost_mp11_files/include/boost/mp11/mpl_tuple.hpp
    - boost_mp11_files/include/boost/mp11/set.hpp
    - boost_mp11_files/include/boost/mp11/tuple.hpp
    - boost_mp11_files/include/boost/mp11/utility.hpp
    - boost_mp11_files/include/boost/mp11/version.hpp
  boost/mp11/detail:
    - boost_mp11_files/include/boost/mp11/detail/config.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_append.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_copy_if.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_count.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_fold.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_front.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_is_list.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_list.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_map_find.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_min_element.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_plus.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_remove_if.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_rename.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_void.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_with_index.hpp
    - boost_mp11_files/include/boost/mp11/detail/mpl_common.hpp

sources:
  ecsact_rt_entt:
    - ecsact_rt_entt/runtime/common.template.hh
    - ecsact_rt_entt/runtime/common.template.cc
    - ecsact_rt_entt/runtime/core.template.cc
    - ecsact_rt_entt/runtime/dynamic.template.cc
  ecsact_runtime/reference/async_reference/detail/c_execution_options:
    - ecsact_runtime/reference/async_reference/detail/c_execution_options/c_execution_options.hh
    - ecsact_runtime/reference/async_reference/detail/c_execution_options/c_execution_options.cc
  ecsact_runtime/reference/async_reference:
    - ecsact_runtime/reference/async_reference/async_reference.hh
    - ecsact_runtime/reference/async_reference/async_reference.cc
    - ecsact_runtime/reference/async_reference/async.cc
  ecsact_runtime/reference/async_reference/tick_manager:
    - ecsact_runtime/reference/async_reference/tick_manager/tick_manager.hh
    - ecsact_runtime/reference/async_reference/tick_manager/tick_manager.cc
  ecsact_runtime/reference/async_reference/callbacks:
    - ecsact_runtime/reference/async_reference/callbacks/async_callbacks.hh
    - ecsact_runtime/reference/async_reference/callbacks/async_callbacks.cc
    - ecsact_runtime/reference/async_reference/callbacks/execution_callbacks.hh
    - ecsact_runtime/reference/async_reference/callbacks/execution_callbacks.cc
  ecsact_runtime/reference/async_reference/util:
    - ecsact_runtime/reference/async_reference/util/util.hh
    - ecsact_runtime/reference/async_reference/util/util.cc
    - ecsact_runtime/reference/async_reference/util/types.hh
  ecsact_runtime/reference/serialize_reference:
    - ecsact_runtime/reference/serialize_reference/serialize_reference.cc
  ecsact_runtime/reference/async_reference/request_id_factory:
    - ecsact_runtime/reference/async_reference/request_id_factory/request_id_factory.hh

share:
  plugins:
    - ecsact_runtime/reference/serialize_reference/codegen/codegen_bin.dll
