name: CI

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jidicula/clang-format-action@v4.13.0
        with: { clang-format-version: "15" }
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Setup Ecsact SDK
        uses: ecsact-dev/github-action@d23575eab73bb667ffa2772ac511608394ab94e5
      - uses: actions/cache@v3
        with:
          path: |
            /Users/runneradmin/AppData/Local/bazelisk
            /Users/runneradmin/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v2
      - run: bazelisk build --config=ci //...
      - run: bazelisk run --config=ci //test
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v3
      - run: bazelisk build --config=ci //...

