name: release

on:
  release:
    types: [published]

jobs:
  release-linux-x64-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v4
      - run: 'bazel build --config=ci //cli:ecsact_rtb'
      - run: 'cp ./bazel-bin/cli/ecsact_rtb ecsact_rtb_${{ github.ref_name }}_linux_x64'
      - run: 'gh release upload ${{ github.ref_name }} ecsact_rtb_${{ github.ref_name }}_linux_x64'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}

  release-windows-x64-binary:
    runs-on: windows-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            /Users/runneradmin/AppData/Local/bazelisk
            /Users/runneradmin/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v4
      - run: 'bazel build --config=ci //cli:ecsact_rtb'
      - run: 'Copy-Item .\bazel-bin\cli\ecsact_rtb.exe -Destination .\ecsact_rtb_${{ github.ref_name }}_windows_x64.exe'
      - run: 'gh release upload ${{ github.ref_name }} ./ecsact_rtb_${{ github.ref_name }}_windows_x64.exe'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}

